JAR-9125 - clean up script, add remove function

diff --git a/scripts/jarvice-db-index-jobs b/scripts/jarvice-db-index-jobs
--- a/scripts/jarvice-db-index-jobs
+++ b/scripts/jarvice-db-index-jobs
@@ -4,6 +4,9 @@ namespace=jarvice-system
 
 function usage {
     cat <<EOF
+This script applies databes indexes to improve performance of some JARVICE
+functions when there are a large number of jobs (> 1,000,000) present in the
+database
 
 Usage:
     $0 [options]
@@ -11,6 +14,9 @@ Usage:
 Options:
     --namespace <kube_namespace>    Kubernetes namespace of JARVICE deployment
                                     (Default: $namespace)
+    --apply                         Apply the indexes
+    --remove                        Remove indexes
+
 EOF
 }
 
@@ -25,6 +31,27 @@ function yes_no() {
       esac
   done
 }
+
+
+
+function add_idx_msg()
+{
+    cat <<EOF
+******* Adding indexes to the jobs table in the database *******
+
+Please ensure there is enough disk space for index creation, since
+this process may increase the database size by 200% or more.
+The changes could take several minutes to apply, depending on the CPU and
+disk speed of the database server, and should be run during a maintenance
+window.
+EOF
+}
+
+function del_idx_msg()
+{
+    echo "******* Removing indexes from the jobs table in the database *******"
+}
+
 
 
 KUBECTL=$(type -p kubectl)
@@ -42,6 +69,22 @@ while [ $# -gt 0 ]; do
             namespace=$2
             shift; shift
             ;;
+
+        --apply)
+            add_idx_msg
+            yes_no
+            echo "* Indexing JARVICE database jobs table in $namespace namespace..."; echo
+            sql=$(cat ../files/jarvice-job-fts-index-add.sql)
+            shift
+            ;;
+
+        --remove)
+            del_idx_msg
+            yes_no
+            echo "* De-indexing JARVICE database jobs table in $namespace namespace..."; echo
+            sql=$(cat ../files/jarvice-job-fts-index-remove.sql)
+            shift
+            ;;
         *)
             usage
             exit 1
@@ -49,30 +92,17 @@ while [ $# -gt 0 ]; do
     esac
 done
 
-
-cat <<EOF
-This script updates the job table for JARVICE to allow the sys-admin
-to navigate the Jobs UI dashboard much more efficiently when there are
-a large number of jobs(upto 10,000,000).
-
-NOTE: Please ensure there is enough disk space for new index creation, since
-the new indexes may increase the database size by 200% or more.
-The changes could take several minutes to apply, depending on the CPU and
-disk speed of the database server, and should be run during a maintenance
-window.
-EOF
-
-yes_no
-
 pod=$($KUBECTL -n $namespace get pods \
         -l component=jarvice-dal \
         --field-selector=status.phase=Running \
         -o jsonpath={.items[0].metadata.name})
-[ -z "$pod" ] && echo "* Could not find jarvice-db pod in $namespace namespace...Exiting..." && exit 1
+[ -z "$pod" ] && \
+    echo "* Could not find jarvice-db pod in $namespace namespace..." && \
+    echo "Exiting..." && exit 1
+
 cmd='mariadb '
+cmd+=' --table'
 cmd+=' --user="$JARVICE_SITE_DBUSER" --password="$JARVICE_SITE_DBPASSWD"'
 cmd+=' --host="$JARVICE_SITE_DBHOST" nimbix'
-echo "* Indexing JARVICE database jobs table in $namespace namespace..."; echo
-sql=$(cat ../files/jarvice-job-fts-index.sql)
 
 $KUBECTL -n $namespace exec $pod -- bash -c "echo '$sql' | $cmd"
