Add ability to add/update/delete nodegroup stacks..

diff --git a/scripts/jarvice-deploy2eks b/scripts/jarvice-deploy2eks
--- a/scripts/jarvice-deploy2eks
+++ b/scripts/jarvice-deploy2eks
@@ -18,13 +18,18 @@ aws_region=us-west-2
 aws_zones=
 helm_name=jarvice
 helm_namespace=jarvice-system
+eks_stack_add=
+eks_stack_update=
+eks_stack_delete=
 
 function jarvice_deploy2eks_usage {
     cat <<EOF
 Usage:
-  $0 [deploy_options]
-  $0 --eks-cluster-delete <name> \\
-    [ --aws-region <aws_region> ]
+  $0 [deploy_options] [eks_cluster_options]
+  $0 --eks-stack-add [eks_cluster_options]
+  $0 --eks-stack-update <number> [eks_cluster_options]
+  $0 --eks-stack-delete <number> [--eks-cluster-name <name>] [--aws-region <aws_region>]
+  $0 --eks-cluster-delete <name> [--aws-region <aws_region>]
 
 Available [deploy_options]:
   --registry-username <username>    Docker registry username for JARVICE system
@@ -38,28 +43,30 @@ Available [deploy_options]:
                                     synchronization
   --jarvice-chart-dir <path>        Alternative JARVICE helm chart directory
                                     (optional)
+  --helm-name <app_release_name>    Helm app release name
+                                    (default: $helm_name)
+  --helm-namespace <k8s_namespace>  Cluster namepace to install release into
+                                    (default: $helm_namespace)
+
+Available [eks_cluster_options]:
+  --aws-region <aws_region>         AWS region for EKS cluster
+                                    (default: $aws_region)
+  --aws-zones <aws_zone_list>       Comma separated zone list for --aws-region
+                                    (initial deploy only, optional)
   --eks-cluster-name <name>         EKS cluster name
                                     (default: $eks_cluster_name)
   --eks-node-type <node_type>       EC2 instance types for EKS nodes
                                     (default: $eks_node_type)
-  --install-nvidia-plugin           Install kubernetes device plugin if
-                                    --eks-node-type has Nvidia GPUs
   --eks-nodes <number>              Number of EKS cluster nodes
                                     (default: $eks_nodes)
   --eks-nodes-max <number>          Autoscale up to maximum number of nodes
                                     (must be greater than --eks-nodes)
   --eks-nodes-vol-size <number>     Size of the nodes' EBS volume in GB
                                     (default: $eks_nodes_vol_size)
-  --aws-region <aws_region>         AWS region for EKS cluster
-                                    (default: $aws_region)
-  --aws-zones <aws_zone_list>       Comma separated zone list for --aws-region
-                                    (optional)
-  --helm-name <app_release_name>    Helm app release name
-                                    (default: $helm_name)
-  --helm-namespace <k8s_namespace>  Cluster namepace to install release into
-                                    (default: $helm_namespace)
+  --install-nvidia-plugin           Install kubernetes device plugin if
+                                    --eks-node-type has Nvidia GPUs
+                                    (initial deploy only, optional)
 
-Cluster [deploy_options]:
 See the following link for available EC2 instance types (--eks-node-type):
 https://aws.amazon.com/ec2/instance-types/
 
@@ -151,6 +158,18 @@ while [ $# -gt 0 ]; do
             helm_namespace=$2
             shift; shift
             ;;
+        --eks-stack-add)
+            eks_stack_add=y
+            shift
+            ;;
+        --eks-stack-update)
+            eks_stack_update=$2
+            shift; shift
+            ;;
+        --eks-stack-delete)
+            eks_stack_delete=$2
+            shift; shift
+            ;;
         *)
             jarvice_deploy2eks_usage
             exit 1
@@ -220,9 +239,10 @@ function strict_version {
     python -c "from distutils.version import StrictVersion;print StrictVersion('$ver') >= StrictVersion('$ver_req');"
 }
 
-function eks_stack_delete {
+function eks_cf_stack_delete {
     stack_name="$1"
 
+    echo
     echo "* Deleting CloudFormation stack '$stack_name'..."
     $AWS --region $aws_region cloudformation \
         delete-stack --stack-name $stack_name
@@ -240,6 +260,119 @@ function eks_stack_delete {
     if [ -n "$status_reason" ]; then
         echo "$status_reason"
     fi
+}
+
+function eks_nodegroup_stack_add_update {
+    nodegroup_id=$1
+
+    stack_name=
+    # Get template body of previous node stack if updating
+    if [ -n "$nodegroup_id" ]; then
+        command=update-stack
+        stack_name="eksctl-$eks_cluster_name-nodegroup-$nodegroup_id"
+        template_body=$($AWS --region $aws_region cloudformation \
+            get-template \
+            --stack-name $stack_name 2>/dev/null | \
+            jq ".TemplateBody")
+    else
+        command=create-stack
+        template_body=$($AWS --region $aws_region cloudformation \
+            get-template \
+            --stack-name eksctl-$eks_cluster_name-nodegroup-0 | \
+            jq ".TemplateBody")
+        nodegroup_id=$($AWS --region $aws_region cloudformation \
+            describe-stacks | \
+            jq -r ".Stacks[] | select(.Parameters[].ParameterValue==\"eksctl-$eks_cluster_name-cluster\").Parameters[] | select(.ParameterKey==\"NodeGroupID\").ParameterValue" | \
+            sort | tail -n 1)
+        nodegroup_id=$((nodegroup_id+1))
+        stack_name="eksctl-$eks_cluster_name-nodegroup-$nodegroup_id"
+    fi
+
+    map=$(cat <<EOF
+{
+    "DeviceName": "/dev/xvda",
+    "Ebs": {
+        "VolumeSize": "$eks_nodes_vol_size",
+        "VolumeType": "gp2",
+        "DeleteOnTermination": true,
+    }
+}
+EOF
+)
+    [ $eks_nodes_max -eq 0 ] && eks_nodes_max=$eks_nodes
+    template_body=$(echo "$template_body" | \
+        jq ".Resources.NodeLaunchConfig.Properties.BlockDeviceMappings = [$map]" | \
+        jq ".Resources.NodeGroup.Properties.DesiredCapacity = \"$eks_nodes\"" | \
+        jq ".Resources.NodeGroup.Properties.MinSize = \"$eks_nodes\"" | \
+        jq ".Resources.NodeGroup.Properties.MaxSize = \"$eks_nodes_max\"")
+
+    if [ "$command" = "update-stack" ]; then
+        echo
+        echo "* Updating CloudFormation stack '$stack_name'..."
+    else
+        echo
+        echo "* Adding CloudFormation stack '$stack_name'..."
+    fi
+
+    $AWS --region $aws_region cloudformation \
+        $command \
+        --stack-name $stack_name \
+        --capabilities CAPABILITY_IAM \
+        --template-body "$template_body" \
+        --tags \
+            Key=eksctl.cluster.k8s.io/v1alpha1/cluster-name,Value=$eks_cluster_name \
+            Key=eksctl.cluster.k8s.io/v1alpha1/nodegroup-id,Value=$nodegroup_id \
+        --parameters \
+            ParameterKey=ClusterName,ParameterValue=$eks_cluster_name \
+            ParameterKey=ClusterStackName,ParameterValue=eksctl-$eks_cluster_name-cluster \
+            ParameterKey=NodeGroupID,ParameterValue=$nodegroup_id >/dev/null
+
+    base_status="CREATE_IN_PROGRESS"
+    [ "$command" = "update-stack" ] && base_status="UPDATE_IN_PROGRESS"
+    status=$base_status
+    while [ "$status" = "$base_status" ]; do
+        echo -n "."
+        sleep 5
+        status=$($AWS --region $aws_region cloudformation \
+            describe-stacks \
+            --stack-name $stack_name --output=json \
+            2>/dev/null || /bin/true)
+        status=$(get_json_value "$status" "['Stacks'][0]['StackStatus']")
+        status_reason=$(get_json_value "$status" "['Stacks'][0]['StackStatusReason']")
+    done
+    echo "$status"
+    if [ -n "$status_reason" ]; then
+        echo "$status_reason"
+        return
+    fi
+
+    echo
+    echo "* Updating aws-auth ConfigMap..."
+    role_arns=$($AWS --region $aws_region cloudformation \
+        describe-stacks | \
+        jq -r ".Stacks[] | select(.Parameters[].ParameterValue==\"eksctl-$eks_cluster_name-cluster\").Outputs[].OutputValue")
+        configmap_yaml=$(cat <<EOF
+apiVersion: v1
+kind: ConfigMap
+metadata:
+  name: aws-auth
+  namespace: kube-system
+data:
+  mapRoles: |
+EOF
+)
+    for role_arn in $role_arns; do
+        configmap_yaml=$(cat <<EOF
+$configmap_yaml
+    - rolearn: $role_arn
+      username: system:node:{{EC2PrivateDNSName}}
+      groups:
+        - system:bootstrappers
+        - system:nodes
+EOF
+)
+    done
+    echo "$configmap_yaml" | $KUBECTL --namespace kube-system apply -f - >/dev/null 2>&1
 }
 
 if [ -n "$eks_cluster_delete" ]; then
@@ -262,13 +395,19 @@ if [ -n "$eks_cluster_delete" ]; then
         --query "SecurityGroups[*].{Name:GroupName}" | grep '^k8s-elb-' \
         || /bin/true)
     AWS_ELB_NAMES=$(echo "$AWS_ELB_SEC_GROUP_NAMES" | sed -e 's/k8s-elb-//')
+    echo
     for elb_name in $AWS_ELB_NAMES; do
         echo "* Deleting AWS elastic load balancer '$elb_name'..."
         $AWS --region $aws_region elb delete-load-balancer \
             --load-balancer-name=$elb_name
     done
 
-    eks_stack_delete "eksctl-$eks_cluster_delete-nodegroup-0"
+    nodegroup_stacks=$($AWS --region $aws_region cloudformation \
+        describe-stacks | \
+        jq -r ".Stacks[] | select(.Parameters[].ParameterValue==\"eksctl-$eks_cluster_delete-cluster\").StackName")
+    for nodegroup_stack in $nodegroup_stacks; do
+        eks_cf_stack_delete "$nodegroup_stack"
+    done
 
     AWS_ELB_SEC_GROUP_IDS=$($AWS --region $aws_region ec2 \
         describe-security-groups --no-paginate --output=text \
@@ -276,13 +415,14 @@ if [ -n "$eks_cluster_delete" ]; then
         --query "SecurityGroups[*].{ID:GroupId}")
         #--filters Name=tag:eksctl.cluster.k8s.io/v1alpha1/cluster-name,Values=$eks_cluster_delete \
 
+    echo
     for group_id in $AWS_ELB_SEC_GROUP_IDS; do
         echo "* Deleting AWS EC2 security group '$group_id'..."
         $AWS --region $aws_region ec2 delete-security-group \
             --group-id=$group_id
     done
 
-    eks_stack_delete "eksctl-$eks_cluster_delete-cluster"
+    eks_cf_stack_delete "eksctl-$eks_cluster_delete-cluster"
 
     #echo "* Deleting EKS cluster '$eks_cluster_delete' in region" \
     #    "'$aws_region'..."
@@ -295,15 +435,57 @@ if [ -n "$eks_cluster_delete" ]; then
     exit 0
 fi
 
-if [ -z "$registry_username" -o -z "$registry_password" -o -z "$jarvice_license" -o -z "$jarvice_username" -o -z "$jarvice_apikey" ]; then
-    echo "Missing credentials and/or license.  Cannot continue."
-    jarvice_deploy2eks_usage
-fi
-
 if [ $eks_nodes_max -gt 0 -a $eks_nodes_max -le $eks_nodes ]; then
     echo "--eks-nodes-max must be greater than --eks-nodes in order to" \
         "enable node auto scaling."
     exit 1
+fi
+
+if [ -n "$eks_stack_add" ]; then
+    set -e
+    check_deps
+
+    if [ -z "$eks_cluster_name" ]; then
+        jarvice_deploy2eks_usage
+    fi
+    eks_nodegroup_stack_add_update
+
+    exit 0
+fi
+
+if [ -n "$eks_stack_update" ]; then
+    set -e
+    check_deps
+
+    if [ -z "$eks_cluster_name" ]; then
+        jarvice_deploy2eks_usage
+    fi
+    eks_nodegroup_stack_add_update $eks_stack_update
+
+    exit 0
+fi
+
+if [ -n "$eks_stack_delete" ]; then
+    set -e
+    check_deps
+
+    if [ "$eks_stack_delete" = "0" ]; then
+        echo "Nodegroup 0 may only be updated, not deleted."
+        exit 1
+    fi
+
+    if [ -z "$eks_cluster_name" ]; then
+        jarvice_deploy2eks_usage
+    fi
+    stack_name="eksctl-$eks_cluster_name-nodegroup-$eks_stack_delete"
+    eks_cf_stack_delete "$stack_name"
+
+    exit 0
+fi
+
+if [ -z "$registry_username" -o -z "$registry_password" -o -z "$jarvice_license" -o -z "$jarvice_username" -o -z "$jarvice_apikey" ]; then
+    echo "Missing credentials and/or license.  Cannot continue."
+    jarvice_deploy2eks_usage
 fi
 
 # Assumes helm chart basedir is one level up from this script
@@ -433,37 +615,7 @@ $EKSCTL create cluster --name $eks_cluster_name \
 
 echo
 echo "* Updating nodegroup stack..."
-# Get template body of node stack newly created by eksctl
-template_body=$($AWS --region $aws_region cloudformation \
-    get-template --stack-name eksctl-$eks_cluster_name-nodegroup-0 | \
-    jq ".TemplateBody")
-
-map=$(cat <<EOF
-{
-    "DeviceName": "/dev/xvda",
-    "Ebs": {
-        "VolumeSize": "$eks_nodes_vol_size",
-        "VolumeType": "gp2",
-        "DeleteOnTermination": true,
-    }
-}
-EOF
-)
-[ $eks_nodes_max -eq 0 ] && eks_nodes_max=$eks_nodes
-template_body=$(echo "$template_body" | \
-    jq ".Resources.NodeLaunchConfig.Properties.BlockDeviceMappings = [$map]" | \
-    jq ".Resources.NodeGroup.Properties.DesiredCapacity = \"$eks_nodes\"" | \
-    jq ".Resources.NodeGroup.Properties.MinSize = \"$eks_nodes\"" | \
-    jq ".Resources.NodeGroup.Properties.MaxSize = \"$eks_nodes_max\"")
-
-$AWS --region $aws_region cloudformation \
-    update-stack --stack-name eksctl-$eks_cluster_name-nodegroup-0 \
-    --capabilities CAPABILITY_IAM \
-    --template-body "$template_body" \
-    --parameters \
-        ParameterKey=ClusterName,ParameterValue=$eks_cluster_name \
-        ParameterKey=ClusterStackName,ParameterValue=eksctl-$eks_cluster_name-cluster \
-        ParameterKey=NodeGroupID,ParameterValue=0 >/dev/null
+eks_nodegroup_stack_add_update 0
 
 echo
 echo "* Waiting for minimum number of nodes to be ready..."
