Remove nfsnolock flex plugin need for jq

diff --git a/files/install-flex-nfs-nolock b/files/install-flex-nfs-nolock
--- a/files/install-flex-nfs-nolock
+++ b/files/install-flex-nfs-nolock
@@ -2,17 +2,17 @@
 
 set -e
 
-if ! type jq >/dev/null 2>&1; then
-    install_pkgs="jq"
-    echo "* Installing '$install_pkgs'..."
-    if [ -e /etc/redhat-release ]; then
-        yum -y install $install_pkgs
-    else
-        apt-get -y update
-        apt-get -y install $install_pkgs
-    fi
-    echo "* Installing '$install_pkgs'...done."
-fi
+#if ! type jq >/dev/null 2>&1; then
+#    install_pkgs="jq"
+#    echo "* Installing '$install_pkgs'..."
+#    if [ -e /etc/redhat-release ]; then
+#        yum -y install $install_pkgs
+#    else
+#        apt-get -y update
+#        apt-get -y install $install_pkgs
+#    fi
+#    echo "* Installing '$install_pkgs'...done."
+#fi
 
 VENDOR=jarvice.io
 DRIVER=nfsnolock
@@ -98,11 +98,17 @@ ismounted() {
 domount() {
 	MNTPATH=$1
 
-	local NFS_SERVER=$(echo $2 | jq -r '.server')
-	local SHARE=$(echo $2 | jq -r '.share')
-	local PROTOCOL=$(echo $2 | jq -r '.protocol')
-	local ATIME=$(echo $2 | jq -r '.atime')
-	local READONLY=$(echo $2 | jq -r '.readonly')
+	#local NFS_SERVER=$(echo $2 | jq -r '.server')
+	#local SHARE=$(echo $2 | jq -r '.share')
+	#local PROTOCOL=$(echo $2 | jq -r '.protocol')
+	#local ATIME=$(echo $2 | jq -r '.atime')
+	#local READONLY=$(echo $2 | jq -r '.readonly')
+
+	local NFS_SERVER=$(echo $2 | grep '"server"' | sed -E 's/.*"server":"([^"]*)".*/\1/')
+	local SHARE=$(echo $2 | grep '"share"' | sed -E 's/.*"share":"([^"]*)".*/\1/')
+	local PROTOCOL=$(echo $2 | grep '"protocol"' | sed -E 's/.*"protocol":"([^"]*)".*/\1/')
+	local ATIME=$(echo $2 | grep '"atime"' | sed -E 's/.*"atime":"([^"]*)".*/\1/')
+	local READONLY=$(echo $2 | grep '"readonly"' | sed -E 's/.*"readonly":"([^"]*)".*/\1/')
 
 	if [ -n "${PROTOCOL}" ]; then
 		PROTOCOL="tcp"
@@ -166,10 +172,10 @@ unmount() {
 
 op=$1
 
-if ! command -v jq >/dev/null 2>&1; then
-	err "{ \"status\": \"Failure\", \"message\": \"'jq' binary not found. Please install jq package before using this driver\"}"
-	exit 1
-fi
+#if ! command -v jq >/dev/null 2>&1; then
+#	err "{ \"status\": \"Failure\", \"message\": \"'jq' binary not found. Please install jq package before using this driver\"}"
+#	exit 1
+#fi
 
 if [ "$op" = "init" ]; then
 	log '{"status": "Success", "capabilities": {"attach": false}}'
